### ISSUE TITLE
Create github workflow pr.yml

### ISSUE THREAD

**Issue by tim-tschiersch** [adorsys/ops-k8s-bootstrap#21]
Use the existing apply.yml (https://github.com/adorsys/ops-k8s-bootstrap/blob/main/.github/workflows/apply.yml) as a guideline for the new pr.yml

- [x] new pr.yml has been created 
- [x] terraform init step is included
- [x] terraform plan step is included
- [x] terraform validate step is included
- [x] terraform tfsec step is included

**Comment by tim-tschiersch** [comment]
Added tfsec step + junit tests 
```
- uses: aquasecurity/tfsec-action@v1.0.0
        id: tfsec
        with:
          additional_args: "--out tfsec.xml"
          soft_fail: true
          format: junit
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'tfsec.xml'
```
